# Generated by Django 3.0 on 2019-12-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_checkeditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='checker',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
