# Generated by Django 3.0 on 2019-12-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_item_checker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='checker',
        ),
        migrations.AlterField(
            model_name='checkeditem',
            name='checker',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
