# Generated by Django 3.0 on 2019-12-07 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191207_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkeditem',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='checkeditem',
            name='checkedItem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checkmark', to='api.Item'),
        ),
    ]
