# Generated by Django 3.0 on 2019-12-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191207_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='checker',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
