# Generated by Django 3.0 on 2019-12-07 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191207_0723'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckedItem',
        ),
    ]
